<a href="https://colab.research.google.com/github/pouyarahmti/Pytorch-Deep-Learning-Bootcamp/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.PyTorch Fundamentals


In [56]:
import torch
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

print(torch.__version__)

2.2.1+cu121


# Introduction to Tensors

### Creating Tensors

 pytorch tensors are created using `torch.tensor()`

In [57]:
# Scalar Tensor

scalar = torch.tensor(7)
scalar

tensor(7)

In [58]:
scalar.ndim

0

In [59]:
# Get tensor back as python int
scalar.item()

7

In [60]:
# Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [61]:
vector.ndim

1

In [62]:
vector.shape

torch.Size([2])

In [63]:
# MATRIX

MATRIX = torch.tensor([[7, 3], [8, 3] ])
MATRIX

tensor([[7, 3],
        [8, 3]])

In [64]:
MATRIX.ndim

2

In [65]:
MATRIX[0][0].item()

7

In [66]:
MATRIX.shape

torch.Size([2, 2])

In [114]:
#TENSOR

TENSOR = torch.tensor([[[1,2], [3,4], [5,5]], [[1,2], [3,4], [5,5]]])

print(TENSOR)

TENSOR.size()

tensor([[[1, 2],
         [3, 4],
         [5, 5]],

        [[1, 2],
         [3, 4],
         [5, 5]]])


torch.Size([2, 3, 2])

In [115]:
TENSOR.ndim

3

### Random tensors

In [117]:
 # Create random tensor

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9022, 0.3785, 0.6522, 0.8740],
        [0.5370, 0.7008, 0.6363, 0.7114],
        [0.0691, 0.0415, 0.8305, 0.6436]])

In [69]:
random_tensor.shape

torch.Size([3, 4])

In [118]:
random_tensor.ndim

2

In [119]:
random_image_size_tensor = torch.rand(size=(224,244,3))
random_image_size_tensor.size()

torch.Size([224, 244, 3])

In [71]:
random_image_tensor = torch.rand(size=(3,224,244))
random_image_tensor

tensor([[[1.3602e-01, 3.3075e-01, 4.5245e-01,  ..., 5.4527e-01,
          5.7463e-01, 8.9601e-02],
         [5.0652e-01, 7.3853e-01, 3.8033e-01,  ..., 3.9398e-01,
          5.3191e-01, 9.3050e-01],
         [4.0001e-02, 6.8244e-01, 5.8331e-01,  ..., 5.4374e-01,
          1.8090e-01, 5.6839e-01],
         ...,
         [8.8719e-01, 8.6301e-01, 1.1351e-01,  ..., 8.2638e-01,
          2.9867e-01, 4.5423e-01],
         [5.3255e-02, 1.3468e-02, 1.0091e-02,  ..., 9.9208e-01,
          4.1973e-01, 9.0986e-01],
         [9.3923e-01, 9.4793e-01, 7.2257e-02,  ..., 6.8572e-01,
          1.8949e-01, 9.4999e-01]],

        [[6.3932e-01, 3.4052e-02, 7.6250e-01,  ..., 9.7665e-01,
          2.4120e-02, 8.2568e-02],
         [4.2020e-01, 7.3729e-01, 7.7777e-01,  ..., 3.2455e-01,
          1.0641e-01, 3.2864e-01],
         [4.4499e-01, 5.2207e-01, 7.6126e-02,  ..., 7.3301e-01,
          6.1533e-01, 6.5473e-01],
         ...,
         [7.2941e-01, 7.9105e-01, 2.4339e-01,  ..., 3.8398e-01,
          8.249

### ZEROS and ones

In [72]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [73]:
# Create a tensor of all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [75]:
# Torch.arange()
one_to_ten = torch.arange(1,11,)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data Types

**Note:** Tensors datatypes is one of 3 big issues you 'll encounter in PyTorch and DeepLearning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not right device

In [77]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.1,6.5,9.2,], dtype=None, device=None, requires_grad=False,)
float_32_tensor

tensor([3.1000, 6.5000, 9.2000])

In [78]:
#Float 16 tensor

float_16_tensor = float_32_tensor.type(dtype=torch.float16)
float_16_tensor

tensor([3.0996, 6.5000, 9.2031], dtype=torch.float16)

In [79]:
result = float_16_tensor * float_32_tensor
result.dtype

torch.float32

In [80]:
int_32_tensor = torch.tensor([3,4, 6], dtype=torch.int32)
int_32_tensor

tensor([3, 4, 6], dtype=torch.int32)

In [81]:
int_32_tensor * float_32_tensor

tensor([ 9.3000, 26.0000, 55.2000])

### Getting information from tensors

`tensor.dtype` and `tensor.shape` and `tensor.device`

In [121]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2459, 0.5878, 0.9542, 0.6630],
        [0.7423, 0.8273, 0.0572, 0.3120],
        [0.2553, 0.8140, 0.0321, 0.8902]])

In [123]:
print(random_tensor)


print(f"Datatype of tensor: {random_tensor.dtype}")
print(f"Shape of tensor: {random_tensor.shape}")
print(f"Device tensor is on: {random_tensor.device}")

tensor([[0.2459, 0.5878, 0.9542, 0.6630],
        [0.7423, 0.8273, 0.0572, 0.3120],
        [0.2553, 0.8140, 0.0321, 0.8902]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Tensor Operations

Ternsor Operations include:
- Addition
- Substraction
- Multiplication
- Division
- Matrix Multiplication


In [82]:
## Create A Tensor
my_tensor = torch.tensor([1,2,3])

my_tensor + 10

tensor([11, 12, 13])

In [83]:
# Multiply a Tensor by 10

my_tensor * 10

tensor([10, 20, 30])

In [84]:
# Subtract Tensor

my_tensor - 10

tensor([-9, -8, -7])

## Matrix Multiplication

two rules should be applied:

1- inner dimension should be same
2- output shape will be like outer shapes

In [85]:
tensor_A = torch.tensor([[1,2,3], [4,5,6], [7,8,9]], dtype=torch.float32)
tensor_B = torch.rand(size=(3,3))

print(tensor_A.dtype)
print(tensor_B.dtype)

torch.matmul(tensor_A, tensor_B)



torch.float32
torch.float32


tensor([[ 1.9209,  3.3669,  3.8136],
        [ 5.2537,  8.3488,  8.9385],
        [ 8.5865, 13.3307, 14.0634]])

## Find Tensor Min, Max, Mean, Sum, (etc.)


In [86]:
tensor = torch.arange(0,100,10)
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [87]:
# Find min

tensor.min(), torch.min(tensor)

(tensor(0), tensor(0))

In [88]:
# Find Max

tensor.max(), torch.max(tensor)

(tensor(90), tensor(90))

In [89]:
# Find Mean

tensor.type(torch.float32).mean(), torch.mean(tensor.type(torch.float32))

(tensor(45.), tensor(45.))

In [90]:
# Find Sum

tensor.sum(), torch.sum(tensor)

(tensor(450), tensor(450))

## Finding the positional min and max

In [91]:
# find minimum value index

tensor.argmin(), torch.argmin(tensor)

(tensor(0), tensor(0))

In [92]:
# find maximum value index

tensor.argmax(), torch.argmax(tensor)

(tensor(9), tensor(9))

# Reshaping, stacking, squeezing and unsqueezing

* reshaping - reshapes an input tensor to a defined shape
* viewing - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* stacking - combine multiple tensors into a single tensor (vstack) and (hstack)
* squeezing - remove all `1` dimensions from a tensor
* unsqueezing - add  a `1` dimension to a tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way.


In [93]:
x = torch.arange(1,10)

x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [94]:
x.reshape(9,1), x.reshape(9,1).shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [95]:
x[0]

tensor(1)

In [96]:
# Change the view of the tensor
# Changing z will also change x because they share the same memory
z = x.view(3,3)
z

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [97]:
# Stack tensors

x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [98]:
x_stacked.squeeze()

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [99]:
x.squeeze()

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape


(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [101]:
print(x_reshaped.squeeze())
x_reshaped.squeeze().shape

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


torch.Size([9])

In [102]:
x_reshaped.squeeze()[0]

tensor(1)

In [103]:
# Unsqueeze a tensor

print(f"Previous Tensor: {x.squeeze()}")
print(f"Previous Tensor Shape: {x.squeeze().shape}")

print("=========================")

print(f"New Tensor: {x.squeeze().unsqueeze(dim=0)}")
print(f"New Tensor Shape: {x.squeeze().unsqueeze(dim=0).shape}")


Previous Tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Previous Tensor Shape: torch.Size([9])
New Tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
New Tensor Shape: torch.Size([1, 9])


In [104]:
# Torch.permute

x_original = torch.rand(size=(244,244,3))
print(x_original)

x_permuted = x_original.permute(2,0,1)
x_permuted

tensor([[[0.4670, 0.1872, 0.2009],
         [0.8991, 0.8289, 0.7740],
         [0.8052, 0.4894, 0.8516],
         ...,
         [0.1366, 0.5190, 0.1764],
         [0.6661, 0.2094, 0.2067],
         [0.7011, 0.9830, 0.9242]],

        [[0.2366, 0.6523, 0.8765],
         [0.8703, 0.3951, 0.4003],
         [0.6208, 0.9945, 0.3907],
         ...,
         [0.9916, 0.3409, 0.7362],
         [0.8402, 0.5280, 0.1251],
         [0.1609, 0.4715, 0.3660]],

        [[0.6914, 0.2253, 0.7930],
         [0.5984, 0.3296, 0.7381],
         [0.1903, 0.8711, 0.0678],
         ...,
         [0.2805, 0.3675, 0.5829],
         [0.0800, 0.9607, 0.9691],
         [0.1394, 0.3926, 0.7780]],

        ...,

        [[0.1422, 0.3710, 0.0837],
         [0.8960, 0.8168, 0.4356],
         [0.6641, 0.6179, 0.1918],
         ...,
         [0.5633, 0.8370, 0.4002],
         [0.8488, 0.8912, 0.2164],
         [0.9688, 0.3515, 0.4597]],

        [[0.2159, 0.6257, 0.1255],
         [0.6736, 0.7596, 0.4113],
         [0.

tensor([[[0.4670, 0.8991, 0.8052,  ..., 0.1366, 0.6661, 0.7011],
         [0.2366, 0.8703, 0.6208,  ..., 0.9916, 0.8402, 0.1609],
         [0.6914, 0.5984, 0.1903,  ..., 0.2805, 0.0800, 0.1394],
         ...,
         [0.1422, 0.8960, 0.6641,  ..., 0.5633, 0.8488, 0.9688],
         [0.2159, 0.6736, 0.9216,  ..., 0.7993, 0.5294, 0.1839],
         [0.9481, 0.7575, 0.5980,  ..., 0.7081, 0.2516, 0.3118]],

        [[0.1872, 0.8289, 0.4894,  ..., 0.5190, 0.2094, 0.9830],
         [0.6523, 0.3951, 0.9945,  ..., 0.3409, 0.5280, 0.4715],
         [0.2253, 0.3296, 0.8711,  ..., 0.3675, 0.9607, 0.3926],
         ...,
         [0.3710, 0.8168, 0.6179,  ..., 0.8370, 0.8912, 0.3515],
         [0.6257, 0.7596, 0.6459,  ..., 0.1967, 0.8464, 0.0643],
         [0.3385, 0.2706, 0.8992,  ..., 0.1631, 0.3979, 0.7108]],

        [[0.2009, 0.7740, 0.8516,  ..., 0.1764, 0.2067, 0.9242],
         [0.8765, 0.4003, 0.3907,  ..., 0.7362, 0.1251, 0.3660],
         [0.7930, 0.7381, 0.0678,  ..., 0.5829, 0.9691, 0.

## Indexing: Select data from a tensor

In [105]:
x = torch.arange(1,10)


x_reshaped = x.reshape(1,3,3)

x_reshaped

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [106]:
x_reshaped[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [107]:
x_reshaped[0][0]

tensor([1, 2, 3])

In [108]:
x_reshaped[0][0][0]

tensor(1)

In [109]:
# You can use ":" to select "all" of  a target dimension

x_reshaped[:,:,0]

tensor([[1, 4, 7]])