## 00.PyTorch Fundamentals


In [ ]:
import torch
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

print(torch.__version__)

2.1.0+cu121


In [ ]:
#Scalar Tensor

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()


7

In [ ]:
# Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX

MATRIX = torch.tensor([[7, 3], [8, 3] ])
MATRIX

tensor([[7, 3],
        [8, 3]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0][0].item()

7

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR

TENSOR = torch.tensor([[[[1,2], [3,4], [5,5]]]])

TENSOR

TENSOR.size()

torch.Size([1, 1, 3, 2])

### Random tensors

In [ ]:
 # Create random tensor

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3149, 0.0156, 0.8499, 0.5516],
        [0.6762, 0.8005, 0.1687, 0.3977],
        [0.1176, 0.8914, 0.9124, 0.4434]])

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
random_image_size_tensor = torch.rand(size=(224,244,3))
random_image_size_tensor

tensor([[[0.6541, 0.0629, 0.4043],
         [0.7330, 0.8204, 0.9424],
         [0.4228, 0.4254, 0.5004],
         ...,
         [0.7579, 0.8379, 0.5648],
         [0.0212, 0.8787, 0.3400],
         [0.9539, 0.3916, 0.5288]],

        [[0.3004, 0.8414, 0.5088],
         [0.2826, 0.9660, 0.3057],
         [0.6184, 0.2723, 0.2239],
         ...,
         [0.2843, 0.4295, 0.4021],
         [0.3098, 0.7973, 0.1181],
         [0.1613, 0.0898, 0.7255]],

        [[0.9332, 0.8960, 0.0067],
         [0.0434, 0.6627, 0.9814],
         [0.7771, 0.9450, 0.2319],
         ...,
         [0.5303, 0.7919, 0.2493],
         [0.7611, 0.1722, 0.3975],
         [0.0916, 0.6201, 0.4574]],

        ...,

        [[0.0559, 0.0078, 0.0472],
         [0.7747, 0.1286, 0.3708],
         [0.9136, 0.1327, 0.7713],
         ...,
         [0.6150, 0.6368, 0.2255],
         [0.3701, 0.6178, 0.9464],
         [0.4793, 0.6887, 0.8222]],

        [[0.8898, 0.7151, 0.0688],
         [0.6108, 0.0471, 0.1609],
         [0.

In [ ]:
random_image_tensor = torch.rand(size=(3,224,244))
random_image_tensor

tensor([[[0.2162, 0.5148, 0.9845,  ..., 0.0167, 0.3731, 0.9892],
         [0.0219, 0.7717, 0.5510,  ..., 0.2331, 0.3578, 0.7218],
         [0.8878, 0.3180, 0.3879,  ..., 0.5791, 0.9804, 0.7951],
         ...,
         [0.2048, 0.5651, 0.9490,  ..., 0.1153, 0.6878, 0.4210],
         [0.1135, 0.6282, 0.0174,  ..., 0.9780, 0.3206, 0.9817],
         [0.9018, 0.6725, 0.4483,  ..., 0.2240, 0.7488, 0.1615]],

        [[0.0340, 0.1554, 0.8548,  ..., 0.4744, 0.5000, 0.0285],
         [0.9333, 0.4175, 0.0822,  ..., 0.0838, 0.3007, 0.9976],
         [0.3411, 0.5954, 0.6839,  ..., 0.1407, 0.3337, 0.9163],
         ...,
         [0.3127, 0.9232, 0.1398,  ..., 0.7249, 0.4157, 0.3502],
         [0.1401, 0.0426, 0.0831,  ..., 0.5416, 0.4848, 0.9582],
         [0.6369, 0.1727, 0.7380,  ..., 0.7174, 0.3119, 0.1090]],

        [[0.3799, 0.8286, 0.8358,  ..., 0.4494, 0.7447, 0.8955],
         [0.7266, 0.0556, 0.6441,  ..., 0.1105, 0.4553, 0.5336],
         [0.7904, 0.0636, 0.5805,  ..., 0.0319, 0.2865, 0.

#### ZEROS and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [ ]:
# User torch.range()
torch.range(0,10)


<ipython-input-65-f0a6fb998290>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# Torch.arange()
one_to_ten = torch.arange(1,11,)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data Types

In [ ]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.1,6.5,9.2,], dtype=None, device=None, requires_grad=False,)
float_32_tensor

tensor([3.1000, 6.5000, 9.2000])

In [ ]:
#Float 16 tensor

float_16_tensor = float_32_tensor.type(dtype=torch.float16)
float_16_tensor

tensor([3.0996, 6.5000, 9.2031], dtype=torch.float16)

In [ ]:
result = float_16_tensor * float_32_tensor
result.dtype

torch.float32

In [ ]:
int_32_tensor = torch.tensor([3,4, 6], dtype=torch.int32)
int_32_tensor

tensor([3, 4, 6], dtype=torch.int32)

In [ ]:
int_32_tensor * float_32_tensor

tensor([ 9.3000, 26.0000, 55.2000])

### Tensor Operations

Ternsor Operations include:
- Addition
- Substraction
- Multiplication
- Division
- Matrix Multiplication


In [ ]:
## Create A Tensor
my_tensor = torch.tensor([1,2,3])

my_tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply a Tensor by 10

my_tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract Tensor

my_tensor - 10

tensor([-9, -8, -7])

## Matrix Multiplication

two rules should be applied:

1- inner dimension should be same
2- output shape will be like outer shapes

In [ ]:
tensor_A = torch.tensor([[1,2,3], [4,5,6], [7,8,9]], dtype=torch.float32)
tensor_B = torch.rand(size=(3,3))

print(tensor_A.dtype)
print(tensor_B.dtype)

torch.matmul(tensor_A, tensor_B)



torch.float32
torch.float32


tensor([[ 1.2789,  1.8234,  3.8045],
        [ 4.3429,  4.8717, 10.3064],
        [ 7.4069,  7.9200, 16.8083]])

## Find Tensor Min, Max, Mean, Sum, (etc.)


In [ ]:
tensor = torch.arange(0,100,10)
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find min

tensor.min(), torch.min(tensor)

(tensor(0), tensor(0))

In [ ]:
# Find Max

tensor.max(), torch.max(tensor)

(tensor(90), tensor(90))

In [ ]:
# Find Mean

tensor.type(torch.float32).mean(), torch.mean(tensor.type(torch.float32))

(tensor(45.), tensor(45.))

In [ ]:
# Find Sum

tensor.sum(), torch.sum(tensor)

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
# find minimum value index

tensor.argmin(), torch.argmin(tensor)

(tensor(0), tensor(0))

In [ ]:
# find maximum value index

tensor.argmax(), torch.argmax(tensor)

(tensor(9), tensor(9))

# Reshaping, stacking, squeezing and unsqueezing

* reshaping - reshapes an input tensor to a defined shape
* viewing - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* stacking - combine multiple tensors into a single tensor (vstack) and (hstack)
* squeezing - remove all `1` dimensions from a tensor
* unsqueezing - add  a `1` dimension to a tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way.


In [ ]:
x = torch.arange(1,10)

x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
x.reshape(9,1), x.reshape(9,1).shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [ ]:
x[0]

tensor(1)

In [ ]:
# Change the view of the tensor
# Changing z will also change x because they share the same memory
z = x.view(3,3)
z

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Stack tensors

x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_stacked.squeeze()

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x.squeeze()

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape


(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
print(x_reshaped.squeeze())
x_reshaped.squeeze().shape

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


torch.Size([9])

In [ ]:
x_reshaped.squeeze()[0]

tensor(1)

In [ ]:
# Unsqueeze a tensor

print(f"Previous Tensor: {x.squeeze()}")
print(f"Previous Tensor Shape: {x.squeeze().shape}")

print("=========================")

print(f"New Tensor: {x.squeeze().unsqueeze(dim=0)}")
print(f"New Tensor Shape: {x.squeeze().unsqueeze(dim=0).shape}")


Previous Tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Previous Tensor Shape: torch.Size([9])
New Tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
New Tensor Shape: torch.Size([1, 9])


In [ ]:
# Torch.permute

x_original = torch.rand(size=(244,244,3))
print(x_original)

x_permuted = x_original.permute(2,0,1)
x_permuted

tensor([[[0.6321, 0.1634, 0.7054],
         [0.1857, 0.9549, 0.1437],
         [0.0735, 0.8369, 0.8626],
         ...,
         [0.1756, 0.8007, 0.7835],
         [0.5489, 0.9044, 0.7568],
         [0.9374, 0.6798, 0.8040]],

        [[0.6444, 0.4382, 0.6126],
         [0.3332, 0.8217, 0.6698],
         [0.1389, 0.4193, 0.6065],
         ...,
         [0.1038, 0.7698, 0.6362],
         [0.7501, 0.6613, 0.0112],
         [0.0749, 0.5969, 0.9207]],

        [[0.7891, 0.8895, 0.0891],
         [0.9283, 0.5905, 0.6979],
         [0.5310, 0.4096, 0.2374],
         ...,
         [0.6343, 0.4437, 0.1663],
         [0.7528, 0.5142, 0.5272],
         [0.8935, 0.9322, 0.5796]],

        ...,

        [[0.1544, 0.2369, 0.3546],
         [0.6674, 0.7363, 0.7373],
         [0.8343, 0.5833, 0.1160],
         ...,
         [0.0808, 0.2375, 0.3084],
         [0.6060, 0.7683, 0.9458],
         [0.1185, 0.8456, 0.3830]],

        [[0.6947, 0.9654, 0.9695],
         [0.2379, 0.5416, 0.8482],
         [0.

tensor([[[0.6321, 0.1857, 0.0735,  ..., 0.1756, 0.5489, 0.9374],
         [0.6444, 0.3332, 0.1389,  ..., 0.1038, 0.7501, 0.0749],
         [0.7891, 0.9283, 0.5310,  ..., 0.6343, 0.7528, 0.8935],
         ...,
         [0.1544, 0.6674, 0.8343,  ..., 0.0808, 0.6060, 0.1185],
         [0.6947, 0.2379, 0.8492,  ..., 0.5232, 0.8909, 0.6698],
         [0.7509, 0.8080, 0.3884,  ..., 0.6769, 0.6691, 0.7014]],

        [[0.1634, 0.9549, 0.8369,  ..., 0.8007, 0.9044, 0.6798],
         [0.4382, 0.8217, 0.4193,  ..., 0.7698, 0.6613, 0.5969],
         [0.8895, 0.5905, 0.4096,  ..., 0.4437, 0.5142, 0.9322],
         ...,
         [0.2369, 0.7363, 0.5833,  ..., 0.2375, 0.7683, 0.8456],
         [0.9654, 0.5416, 0.1294,  ..., 0.5230, 0.9644, 0.8961],
         [0.2960, 0.5311, 0.4948,  ..., 0.7362, 0.9958, 0.9631]],

        [[0.7054, 0.1437, 0.8626,  ..., 0.7835, 0.7568, 0.8040],
         [0.6126, 0.6698, 0.6065,  ..., 0.6362, 0.0112, 0.9207],
         [0.0891, 0.6979, 0.2374,  ..., 0.1663, 0.5272, 0.

## Indexing: Select data from a tensor

In [ ]:
x = torch.arange(1,10)


x_reshaped = x.reshape(1,3,3)

x_reshaped

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x_reshaped[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x_reshaped[0][0]

tensor([1, 2, 3])

In [ ]:
x_reshaped[0][0][0]

tensor(1)

In [ ]:
# You can use ":" to select "all" of  a target dimension

x_reshaped[:,:,0]

tensor([[1, 4, 7]])

In [ ]:
def fib()