<a href="https://colab.research.google.com/github/pouyarahmti/Pytorch-Deep-Learning-Bootcamp/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.PyTorch Fundamentals


In [59]:
import torch
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

print(torch.__version__)

2.2.1+cu121


# Introduction to Tensors

### Creating Tensors

 pytorch tensors are created using `torch.tensor()`

In [60]:
# Scalar Tensor

scalar = torch.tensor(7)
scalar

tensor(7)

In [61]:
scalar.ndim

0

In [62]:
# Get tensor back as python int
scalar.item()

7

In [63]:
# Vector

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [64]:
vector.ndim

1

In [65]:
vector.shape

torch.Size([2])

In [66]:
# MATRIX

MATRIX = torch.tensor([[7, 3], [8, 3] ])
MATRIX

tensor([[7, 3],
        [8, 3]])

In [67]:
MATRIX.ndim

2

In [68]:
MATRIX[0][0].item()

7

In [69]:
MATRIX.shape

torch.Size([2, 2])

In [70]:
#TENSOR

TENSOR = torch.tensor([[[1,2], [3,4], [5,5]], [[1,2], [3,4], [5,5]]])

print(TENSOR)

TENSOR.size()

tensor([[[1, 2],
         [3, 4],
         [5, 5]],

        [[1, 2],
         [3, 4],
         [5, 5]]])


torch.Size([2, 3, 2])

In [71]:
TENSOR.ndim

3

### Random tensors

In [72]:
 # Create random tensor

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8328, 0.1859, 0.7255, 0.9999],
        [0.4362, 0.4740, 0.4294, 0.5360],
        [0.5022, 0.8390, 0.7010, 0.5882]])

In [73]:
random_tensor.shape

torch.Size([3, 4])

In [74]:
random_tensor.ndim

2

In [75]:
random_image_size_tensor = torch.rand(size=(224,244,3))
random_image_size_tensor.size()

torch.Size([224, 244, 3])

In [76]:
random_image_tensor = torch.rand(size=(3,224,244))
random_image_tensor

tensor([[[0.8505, 0.5238, 0.1249,  ..., 0.4133, 0.8153, 0.3952],
         [0.4165, 0.8476, 0.1674,  ..., 0.9325, 0.1595, 0.6280],
         [0.1095, 0.6230, 0.0330,  ..., 0.2445, 0.4739, 0.8054],
         ...,
         [0.9942, 0.2296, 0.2318,  ..., 0.9135, 0.4737, 0.0500],
         [0.6517, 0.3838, 0.9441,  ..., 0.8429, 0.3583, 0.1924],
         [0.2333, 0.8955, 0.6275,  ..., 0.4883, 0.6903, 0.7050]],

        [[0.6058, 0.1258, 0.2949,  ..., 0.4639, 0.4596, 0.6938],
         [0.6484, 0.8744, 0.8753,  ..., 0.3700, 0.3943, 0.3870],
         [0.0938, 0.6788, 0.6772,  ..., 0.4288, 0.2805, 0.1421],
         ...,
         [0.7509, 0.4193, 0.1516,  ..., 0.8142, 0.3725, 0.9137],
         [0.7381, 0.3097, 0.3823,  ..., 0.1202, 0.8572, 0.8003],
         [0.9357, 0.5192, 0.4669,  ..., 0.4658, 0.3151, 0.9292]],

        [[0.4250, 0.2171, 0.3808,  ..., 0.9953, 0.3729, 0.9751],
         [0.6641, 0.8581, 0.3017,  ..., 0.3332, 0.3055, 0.6830],
         [0.2363, 0.4106, 0.5611,  ..., 0.6385, 0.1890, 0.

### ZEROS and ones

In [77]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [78]:
# Create a tensor of all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [79]:
# Torch.arange()
one_to_ten = torch.arange(1,11,)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data Types

**Note:** Tensors datatypes is one of 3 big issues you 'll encounter in PyTorch and DeepLearning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not right device

In [81]:
# Float 32 tensor

float_32_tensor = torch.tensor([3.1,6.5,9.2,], dtype=None, device=None, requires_grad=False,)
float_32_tensor

tensor([3.1000, 6.5000, 9.2000])

In [82]:
#Float 16 tensor

float_16_tensor = float_32_tensor.type(dtype=torch.float16)
float_16_tensor

tensor([3.0996, 6.5000, 9.2031], dtype=torch.float16)

In [83]:
result = float_16_tensor * float_32_tensor
result.dtype

torch.float32

In [84]:
int_32_tensor = torch.tensor([3,4, 6], dtype=torch.int32)
int_32_tensor

tensor([3, 4, 6], dtype=torch.int32)

In [85]:
int_32_tensor * float_32_tensor

tensor([ 9.3000, 26.0000, 55.2000])

### Getting information from tensors

`tensor.dtype` and `tensor.shape` and `tensor.device`

In [86]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4868, 0.9594, 0.6232, 0.4290],
        [0.3001, 0.1338, 0.8048, 0.5929],
        [0.7508, 0.9722, 0.7010, 0.5843]])

In [87]:
print(random_tensor)


print(f"Datatype of tensor: {random_tensor.dtype}")
print(f"Shape of tensor: {random_tensor.shape}")
print(f"Device tensor is on: {random_tensor.device}")

tensor([[0.4868, 0.9594, 0.6232, 0.4290],
        [0.3001, 0.1338, 0.8048, 0.5929],
        [0.7508, 0.9722, 0.7010, 0.5843]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Tensor Operations

Ternsor Operations include:
- Addition
- Substraction
- Multiplication
- Division
- Matrix Multiplication


In [88]:
## Create A Tensor
my_tensor = torch.tensor([1,2,3])

my_tensor + 10

tensor([11, 12, 13])

In [89]:
# Multiply a Tensor by 10

my_tensor * 10

tensor([10, 20, 30])

In [90]:
# Subtract Tensor

my_tensor - 10

tensor([-9, -8, -7])

## Matrix Multiplication

two rules should be applied:

1- inner dimension should be same
2- output shape will be like outer shapes

In [91]:
tensor_A = torch.tensor([[1,2,3], [4,5,6], [7,8,9]], dtype=torch.float32)
tensor_B = torch.rand(size=(3,3))

print(tensor_A.dtype)
print(tensor_B.dtype)

torch.matmul(tensor_A, tensor_B)



torch.float32
torch.float32


tensor([[2.2384, 2.0553, 1.9964],
        [4.8670, 4.5172, 5.1266],
        [7.4955, 6.9792, 8.2568]])

## Find Tensor Min, Max, Mean, Sum, (etc.)


In [92]:
tensor = torch.arange(0,100,10)
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [93]:
# Find min

tensor.min(), torch.min(tensor)

(tensor(0), tensor(0))

In [94]:
# Find Max

tensor.max(), torch.max(tensor)

(tensor(90), tensor(90))

In [95]:
# Find Mean
tensor.type(torch.float32).mean(), torch.mean(tensor.type(torch.float32))

(tensor(45.), tensor(45.))

In [96]:
# Find Sum

tensor.sum(), torch.sum(tensor)

(tensor(450), tensor(450))

## Finding the positional min and max

In [97]:
# find minimum value index

tensor.argmin(), torch.argmin(tensor)

(tensor(0), tensor(0))

In [98]:
# find maximum value index

tensor.argmax(), torch.argmax(tensor)

(tensor(9), tensor(9))

# Reshaping, stacking, squeezing and unsqueezing

* reshaping - reshapes an input tensor to a defined shape
* viewing - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* stacking - combine multiple tensors into a single tensor (vstack) and (hstack)
* squeezing - remove all `1` dimensions from a tensor
* unsqueezing - add  a `1` dimension to a tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way.


In [99]:
x = torch.arange(1,10)

x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [100]:
x.reshape(9,1), x.reshape(9,1).shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [101]:
x[0]

tensor(1)

In [102]:
# Change the view of the tensor
# Changing z will also change x because they share the same memory
z = x.view(3,3)
z

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [103]:
# Stack tensors

x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [104]:
x_stacked.squeeze()

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [105]:
x.squeeze()

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape


(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [107]:
print(x_reshaped.squeeze())
x_reshaped.squeeze().shape

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


torch.Size([9])

In [108]:
x_reshaped.squeeze()[0]

tensor(1)

In [109]:
# Unsqueeze a tensor

print(f"Previous Tensor: {x.squeeze()}")
print(f"Previous Tensor Shape: {x.squeeze().shape}")

print("=========================")

print(f"New Tensor: {x.squeeze().unsqueeze(dim=0)}")
print(f"New Tensor Shape: {x.squeeze().unsqueeze(dim=0).shape}")


Previous Tensor: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Previous Tensor Shape: torch.Size([9])
New Tensor: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
New Tensor Shape: torch.Size([1, 9])


In [110]:
# Torch.permute

x_original = torch.rand(size=(244,244,3))
print(x_original)

x_permuted = x_original.permute(2,0,1)
x_permuted

tensor([[[0.6265, 0.2080, 0.3440],
         [0.3363, 0.3320, 0.3169],
         [0.6458, 0.3599, 0.1699],
         ...,
         [0.4732, 0.4409, 0.1528],
         [0.4918, 0.1598, 0.0607],
         [0.8909, 0.9963, 0.4607]],

        [[0.1011, 0.2146, 0.6395],
         [0.1058, 0.3309, 0.5961],
         [0.7474, 0.1508, 0.4832],
         ...,
         [0.0913, 0.4687, 0.1453],
         [0.9691, 0.8547, 0.5804],
         [0.2842, 0.6451, 0.5511]],

        [[0.8469, 0.1135, 0.2203],
         [0.4165, 0.6078, 0.1320],
         [0.4885, 0.7853, 0.6733],
         ...,
         [0.4213, 0.9839, 0.8744],
         [0.1873, 0.0994, 0.3061],
         [0.9430, 0.8310, 0.0101]],

        ...,

        [[0.5919, 0.9855, 0.6262],
         [0.9994, 0.6544, 0.9145],
         [0.6053, 0.6982, 0.3033],
         ...,
         [0.3503, 0.5540, 0.2487],
         [0.8136, 0.8029, 0.0984],
         [0.7792, 0.2482, 0.3999]],

        [[0.3366, 0.6575, 0.1572],
         [0.3326, 0.4891, 0.0588],
         [0.

tensor([[[0.6265, 0.3363, 0.6458,  ..., 0.4732, 0.4918, 0.8909],
         [0.1011, 0.1058, 0.7474,  ..., 0.0913, 0.9691, 0.2842],
         [0.8469, 0.4165, 0.4885,  ..., 0.4213, 0.1873, 0.9430],
         ...,
         [0.5919, 0.9994, 0.6053,  ..., 0.3503, 0.8136, 0.7792],
         [0.3366, 0.3326, 0.7835,  ..., 0.8086, 0.9053, 0.7529],
         [0.4697, 0.6048, 0.5668,  ..., 0.4396, 0.2958, 0.1518]],

        [[0.2080, 0.3320, 0.3599,  ..., 0.4409, 0.1598, 0.9963],
         [0.2146, 0.3309, 0.1508,  ..., 0.4687, 0.8547, 0.6451],
         [0.1135, 0.6078, 0.7853,  ..., 0.9839, 0.0994, 0.8310],
         ...,
         [0.9855, 0.6544, 0.6982,  ..., 0.5540, 0.8029, 0.2482],
         [0.6575, 0.4891, 0.4513,  ..., 0.5287, 0.4564, 0.5211],
         [0.9235, 0.5318, 0.8665,  ..., 0.4635, 0.2105, 0.1678]],

        [[0.3440, 0.3169, 0.1699,  ..., 0.1528, 0.0607, 0.4607],
         [0.6395, 0.5961, 0.4832,  ..., 0.1453, 0.5804, 0.5511],
         [0.2203, 0.1320, 0.6733,  ..., 0.8744, 0.3061, 0.

## Indexing: Select data from a tensor

In [111]:
x = torch.arange(1,10)


x_reshaped = x.reshape(1,3,3)

x_reshaped

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [112]:
x_reshaped[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [113]:
x_reshaped[0][0]

tensor([1, 2, 3])

In [114]:
x_reshaped[0][0][0]

tensor(1)

In [115]:
# You can use ":" to select "all" of  a target dimension

x_reshaped[:,:,0]

tensor([[1, 4, 7]])

In [119]:
# Get all the values of the 0th dimension from the 1st dimension
x_reshaped[:, 1]

tensor([[4, 5, 6]])

In [120]:
# Get the first two values of the 0th dimension from the 1st dimension
x_reshaped[:, 1, :2]

tensor([[4, 5]])

In [121]:
# Setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

Using device: cpu


In [122]:
tensor = torch.tensor([1,2,3])

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [123]:
tensor_on_cpu = tensor_on_gpu.cpu()
tensor_on_cpu

tensor([1, 2, 3])